### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by YuantongL** [tyler-johnson/couchdb-auth-proxy#6]
Hi, I'm using this for one of my projects. Does this support CORS? I'm using PouchDB replicate the remote database, it works fine when I run locally in NodeJS, then if I try replicate using browser, it gave me the following error message:

"XMLHttpRequest cannot load https://.....MY URL...... Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 406."

I'm thinking it's a CORS issue.

**Comment by tyler-johnson** [comment]
This does not support CORS out of the box, however since this is just an Express middleware adding CORS support is easy with the [`cors`](http://ghub.io/cors) package on NPM.

Something like this would do the trick:

```js
const express = require("express");
const cors = require("cors");
const couchdbProxy = require("couchdb-auth-proxy");

const app = express();

app.use(cors());

app.use(couchdbProxy(function() {
  // admin party!
  return {
    name: null,
    roles: [ "_admin" ]
  };
}));

app.listen(3000);
```
